apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order-backend
        image: shajalahamedcse/order:0.0.1
        ports:
        - containerPort: 80
        env:
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:5000"
