apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30038

  selector:
    app: order
