apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  #type: NodePort
  ports:
  - port: 5000
    protocol: TCP
   # nodePort: 30036

  selector:
    app: payment
